### ISSUE TITLE
PubMed dataset run time error

### ISSUE THREAD

**Issue by NicksonCheng** [scottjiao/SlotGAT_ICML23#4]
I execute `python run_train_slotGAT_on_all_dataset.py` with PubMed dataset got the following error, how could I fixed it?

/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449183005/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [141,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/home/resourceBurglar/Heterogeneous/SlotGAT_ICML23/NC/methods/SlotGAT/run_analysis.py", line 544, in <module>
    run_model_DBLP(trial=None)
  File "/home/resourceBurglar/Heterogeneous/SlotGAT_ICML23/NC/methods/SlotGAT/run_analysis.py", line 350, in run_model_DBLP
    logits,_ = net(features_list, e_feat) 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/resourceBurglar/anaconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/resourceBurglar/anaconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/resourceBurglar/Heterogeneous/SlotGAT_ICML23/NC/methods/SlotGAT/GNN.py", line 217, in forward
    h, res_attn = self.gat_layers[l](self.g, h, e_feat,get_out=get_out, res_attn=res_attn)   #num_nodes*num_heads*(num_ntype*hidden_dim)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/resourceBurglar/anaconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/resourceBurglar/anaconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/resourceBurglar/Heterogeneous/SlotGAT_ICML23/NC/methods/SlotGAT/conv.py", line 132, in forward
    ee = (e_feat * self.attn_e).sum(dim=-1).unsqueeze(-1) if self._edge_feats else 0  #(-1, self._num_heads, 1) 
          ~~~~~~~^~~~~~~~~~~~~
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by scottjiao** [comment]
It seems like to be errors on File "/home/resourceBurglar/Heterogeneous/SlotGAT_ICML23/NC/methods/SlotGAT/conv.py", line 132, code "ee = (e_feat * self.attn_e).sum(dim=-1).unsqueeze(-1) if self._edge_feats else 0 #(-1, self._num_heads, 1)".

This code is for processing edge type features. I suggest you to ablate this part to see further details. If you get any updates, please let me know it.
